/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 apps/presento-web/public/scenes/scene-v3.glb --types --shadows --keepnames --root
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

import { ScreenHtml } from '../components/screen-html.component';

type GLTFResult = GLTF & {
  nodes: {
    Bolt: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt001: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt002: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt003: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt004: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt005: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt006: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt007: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt008: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    back_camera_border01: THREE.Mesh;
    back_camera_border_part_01: THREE.Mesh;
    back_camera_border_part_02: THREE.Mesh;
    back_camera_border_part_03: THREE.Mesh;
    back_camera_glass01: THREE.Mesh;
    back_camera_lens01: THREE.Mesh;
    back_camera_lens_glass01: THREE.Mesh;
    back_flash_border01: THREE.Mesh;
    back_flash_border_part_01: THREE.Mesh;
    back_flash_glass01: THREE.Mesh;
    back_flash_lens01: THREE.Mesh;
    back_flash_lens02: THREE.Mesh;
    back_glass01: THREE.Mesh;
    back_glass_part_01: THREE.Mesh;
    back_panel01: THREE.Mesh;
    back_panel_logo01: THREE.Mesh;
    back_panel_part_01: THREE.Mesh;
    back_panel_part_02: THREE.Mesh;
    body_side_panel01: THREE.Mesh;
    body_side_panel_bolts01: THREE.Mesh;
    body_side_panel_button01: THREE.Mesh;
    body_side_panel_buttons_part_01: THREE.Mesh;
    body_side_panel_buttons_part_02: THREE.Mesh;
    body_side_panel_dynamic01: THREE.Mesh;
    body_side_panel_part_01: THREE.Mesh;
    body_side_panel_part_02: THREE.Mesh;
    body_side_panel_part_03: THREE.Mesh;
    front_camera_part_01: THREE.Mesh;
    front_glass01: THREE.Mesh;
    front_panel01: THREE.Mesh;
    screen01: THREE.Mesh;
    screen_border01: THREE.Mesh;
    screen_part_03: THREE.Mesh;
    usb01: THREE.Mesh;
    usb_part_01: THREE.Mesh;
    Cube: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    ['Logo1.001']: THREE.MeshStandardMaterial;
    ['Metal-Black.001']: THREE.MeshStandardMaterial;
    ['Logo.rim center.001']: THREE.MeshStandardMaterial;
    ['Cromium.001']: THREE.MeshStandardMaterial;
    ['Messing.001']: THREE.MeshStandardMaterial;
    ['Car rubber wheel.001']: THREE.MeshPhysicalMaterial;
    ['Car rubber Glanzwheel.002']: THREE.MeshPhysicalMaterial;
    rot: THREE.MeshStandardMaterial;
    Weis: THREE.MeshStandardMaterial;
    plastic_black: THREE.MeshStandardMaterial;
    metal_black: THREE.MeshStandardMaterial;
    back_black: THREE.MeshStandardMaterial;
    mat_plastic_gray_dark: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    camera_lens: THREE.MeshStandardMaterial;
    glass_falsh: THREE.MeshStandardMaterial;
    chrome: THREE.MeshStandardMaterial;
    mat_white: THREE.MeshStandardMaterial;
    glossy_yellow: THREE.MeshStandardMaterial;
    matte_glass: THREE.MeshStandardMaterial;
    ['mat_black.001']: THREE.MeshStandardMaterial;
    chrome_logo_black: THREE.MeshStandardMaterial;
    mat_black: THREE.MeshStandardMaterial;
    glossy_black: THREE.MeshStandardMaterial;
    aluminium_black: THREE.MeshStandardMaterial;
    screen: THREE.MeshStandardMaterial;
    text_black: THREE.MeshStandardMaterial;
    mat_gray_dark: THREE.MeshStandardMaterial;
    gold: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function SceneModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scenes/scene-v3.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN"
        position={[0.001, -0.06, -0.033]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt"
          castShadow
          receiveShadow
          geometry={nodes.Bolt.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group name="Tire_Yokohama_ADVAN_Neova_AD08RS" position={[0, 0.342, 0]}>
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN001"
        position={[0.001, -0.019, -0.033]}
        rotation={[0, 0.051, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt001"
          castShadow
          receiveShadow
          geometry={nodes.Bolt001.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore001"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS001"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN002"
        position={[0.001, 0.022, -0.033]}
        rotation={[0, 0.073, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt002"
          castShadow
          receiveShadow
          geometry={nodes.Bolt002.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore002"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS002"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN003"
        position={[0.001, 0.064, -0.033]}
        rotation={[0, 0.073, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt003"
          castShadow
          receiveShadow
          geometry={nodes.Bolt003.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore003"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS003"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN004"
        position={[0.1, -0.06, -0.071]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt004"
          castShadow
          receiveShadow
          geometry={nodes.Bolt004.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore004"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS004"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN005"
        position={[0.1, -0.019, -0.071]}
        rotation={[0, 0.266, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt005"
          castShadow
          receiveShadow
          geometry={nodes.Bolt005.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore005"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS005"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN006"
        position={[0.059, -0.005, -0.07]}
        rotation={[0.368, -0.751, 0.257]}
        scale={0.154}
      >
        <mesh
          name="Bolt006"
          castShadow
          receiveShadow
          geometry={nodes.Bolt006.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore006"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS006"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN007"
        position={[-0.045, -0.06, 0.066]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt007"
          castShadow
          receiveShadow
          geometry={nodes.Bolt007.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore007"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS007"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN008"
        position={[-0.045, -0.018, 0.066]}
        rotation={[0, 0.115, Math.PI / 2]}
        scale={0.154}
      >
        <mesh
          name="Bolt008"
          castShadow
          receiveShadow
          geometry={nodes.Bolt008.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore008"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS008"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Device_Collection"
        position={[-0.014, -0.007, 0.025]}
        rotation={[-0.154, 0.573, 0.084]}
      >
        <group name="Apple_iPhone_14_Pro_Space_Black" scale={0.01}>
          <mesh
            name="back_camera_border01"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_border01.geometry}
            material={materials.plastic_black}
            position={[1.253, 4.984, -0.535]}
          />
          <mesh
            name="back_camera_border_part_01"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_border_part_01.geometry}
            material={materials.metal_black}
            position={[1.253, 4.981, -0.441]}
          />
          <mesh
            name="back_camera_border_part_02"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_border_part_02.geometry}
            material={materials.back_black}
            position={[1.253, 4.981, -0.545]}
          />
          <mesh
            name="back_camera_border_part_03"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_border_part_03.geometry}
            material={materials.mat_plastic_gray_dark}
            position={[1.298, 4.805, -0.423]}
          />
          <mesh
            name="back_camera_glass01"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_glass01.geometry}
            material={materials.glass}
            position={[1.253, 4.981, -0.58]}
          />
          <mesh
            name="back_camera_lens01"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_lens01.geometry}
            material={materials.camera_lens}
            position={[1.307, 4.963, -0.412]}
          />
          <mesh
            name="back_camera_lens_glass01"
            castShadow
            receiveShadow
            geometry={nodes.back_camera_lens_glass01.geometry}
            material={materials.glass}
            position={[0.356, 4.978, -0.462]}
          />
          <mesh
            name="back_flash_border01"
            castShadow
            receiveShadow
            geometry={nodes.back_flash_border01.geometry}
            material={materials.glass_falsh}
            position={[0.359, 6.336, -0.282]}
          />
          <mesh
            name="back_flash_border_part_01"
            castShadow
            receiveShadow
            geometry={nodes.back_flash_border_part_01.geometry}
            material={materials.chrome}
            position={[0.359, 6.336, -0.227]}
          />
          <mesh
            name="back_flash_glass01"
            castShadow
            receiveShadow
            geometry={nodes.back_flash_glass01.geometry}
            material={materials.glass}
            position={[0.359, 6.336, -0.355]}
          />
          <mesh
            name="back_flash_lens01"
            castShadow
            receiveShadow
            geometry={nodes.back_flash_lens01.geometry}
            material={materials.mat_white}
            position={[0.359, 6.336, -0.261]}
          />
          <mesh
            name="back_flash_lens02"
            castShadow
            receiveShadow
            geometry={nodes.back_flash_lens02.geometry}
            material={materials.glossy_yellow}
            position={[0.359, 6.336, -0.249]}
          />
          <mesh
            name="back_glass01"
            castShadow
            receiveShadow
            geometry={nodes.back_glass01.geometry}
            material={materials.matte_glass}
            position={[0.003, 0, -0.29]}
          />
          <mesh
            name="back_glass_part_01"
            castShadow
            receiveShadow
            geometry={nodes.back_glass_part_01.geometry}
            material={materials.glass}
            position={[1.233, 4.98, -0.37]}
          />
          <mesh
            name="back_panel01"
            castShadow
            receiveShadow
            geometry={nodes.back_panel01.geometry}
            material={materials['mat_black.001']}
            position={[0.003, 0, -0.268]}
          />
          <mesh
            name="back_panel_logo01"
            castShadow
            receiveShadow
            geometry={nodes.back_panel_logo01.geometry}
            material={materials.chrome_logo_black}
            position={[-0.028, 0.087, -0.182]}
          />
          <mesh
            name="back_panel_part_01"
            castShadow
            receiveShadow
            geometry={nodes.back_panel_part_01.geometry}
            material={materials['mat_black.001']}
            position={[1.233, 4.98, -0.332]}
          />
          <mesh
            name="back_panel_part_02"
            castShadow
            receiveShadow
            geometry={nodes.back_panel_part_02.geometry}
            material={materials.mat_black}
            position={[1.194, 4.726, -0.084]}
          />
          <mesh
            name="body_side_panel01"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel01.geometry}
            material={materials.metal_black}
            position={[0.003, 0, 0.192]}
          />
          <mesh
            name="body_side_panel_bolts01"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_bolts01.geometry}
            material={materials.chrome}
            position={[0.003, -7.354, 0.193]}
          />
          <mesh
            name="body_side_panel_button01"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_button01.geometry}
            material={materials.metal_black}
            position={[3.595, 1.815, 0.192]}
          />
          <mesh
            name="body_side_panel_buttons_part_01"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_buttons_part_01.geometry}
            material={materials.metal_black}
            position={[-3.588, 2.178, 0.192]}
          />
          <mesh
            name="body_side_panel_buttons_part_02"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_buttons_part_02.geometry}
            material={materials.metal_black}
            position={[-3.566, 4.236, 0.191]}
          />
          <mesh
            name="body_side_panel_dynamic01"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_dynamic01.geometry}
            material={materials.glossy_black}
            position={[0.216, -7.323, 0.192]}
          />
          <mesh
            name="body_side_panel_part_01"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_part_01.geometry}
            material={materials.aluminium_black}
            position={[0.003, 0, 0.192]}
          />
          <mesh
            name="body_side_panel_part_02"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_part_02.geometry}
            material={materials.aluminium_black}
            position={[3.578, -2.01, 0.192]}
          />
          <mesh
            name="body_side_panel_part_03"
            castShadow
            receiveShadow
            geometry={nodes.body_side_panel_part_03.geometry}
            material={materials.mat_black}
            position={[-0.035, -1.85, 0.183]}
          />
          <mesh
            name="front_camera_part_01"
            castShadow
            receiveShadow
            geometry={nodes.front_camera_part_01.geometry}
            material={materials.mat_black}
            position={[0.003, 6.757, 0.453]}
          />
          <mesh
            name="front_glass01"
            castShadow
            receiveShadow
            geometry={nodes.front_glass01.geometry}
            material={materials.glass}
            position={[0.003, 0, 0.578]}
          />
          <mesh
            name="front_panel01"
            castShadow
            receiveShadow
            geometry={nodes.front_panel01.geometry}
            material={materials.back_black}
            position={[0.003, 0, 0.543]}
          />
          <mesh
            name="screen01"
            castShadow
            receiveShadow
            geometry={nodes.screen01.geometry}
            position={[0.003, 0, 0.542]}
          >
            <meshStandardMaterial transparent opacity={0} />
            <ScreenHtml device="iphone-14" />
          </mesh>
          <mesh
            name="screen_border01"
            castShadow
            receiveShadow
            geometry={nodes.screen_border01.geometry}
            material={materials.text_black}
            position={[0.003, 0, 0.542]}
          />
          <mesh
            name="screen_part_03"
            castShadow
            receiveShadow
            geometry={nodes.screen_part_03.geometry}
            material={materials.mat_gray_dark}
            position={[0.009, 6.555, 0.542]}
          />
          <mesh
            name="usb01"
            castShadow
            receiveShadow
            geometry={nodes.usb01.geometry}
            material={materials.chrome}
            position={[0.002, -6.943, 0.192]}
          />
          <mesh
            name="usb_part_01"
            castShadow
            receiveShadow
            geometry={nodes.usb_part_01.geometry}
            material={materials.gold}
            position={[0.003, -6.951, 0.167]}
          />
        </group>
      </group>
      <PerspectiveCamera
        name="Camera"
        makeDefault
        far={1000}
        near={0.1}
        fov={22.895}
        position={[0.143, -0.026, 0.443]}
        rotation={[0.06, 0.376, -0.022]}
        scale={0.051}
      />
      <spotLight
        name="Spot"
        intensity={5000}
        castShadow
        shadow-mapSize-width={2048} // Increased shadow map resolution
        shadow-mapSize-height={2048} // Increased shadow map resolution
        shadow-bias={-0.0001} // Bias to reduce shadow acne
        angle={Math.PI / 4}
        penumbra={1}
        decay={2}
        color="#fff6dd"
        position={[0.038, 0.572, -0.078]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <spotLight
        name="Spot001"
        intensity={3000}
        castShadow
        shadow-mapSize-width={2048} // Increased shadow map resolution
        shadow-mapSize-height={2048} // Increased shadow map resolution
        shadow-bias={-0.0001} // Bias to reduce shadow acne
        angle={Math.PI / 4}
        penumbra={1}
        decay={2}
        color="#f933ff"
        position={[0.424, 0.482, 0.055]}
        rotation={[-1.426, 0.775, 1.366]}
      />
      <spotLight
        name="Spot002"
        intensity={3000}
        castShadow
        shadow-mapSize-width={2048} // Increased shadow map resolution
        shadow-mapSize-height={2048} // Increased shadow map resolution
        shadow-bias={-0.0001} // Bias to reduce shadow acne
        angle={Math.PI / 4}
        penumbra={1}
        decay={2}
        color="#77ffd5"
        position={[-0.256, 0.564, 0.208]}
        rotation={[-1.204, -0.436, -1.457]}
      />
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
        position={[0.001, -0.132, -0.033]}
        scale={0.051}
      />
      <mesh
        name="Plane"
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0.001, -0.361, -0.033]}
        scale={0.051}
      />
    </group>
  );
}

useGLTF.preload('/scenes/scene-v3.glb');
