/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 apps/presento-web/public/scenes/scene-v3.glb --types --shadows --keepnames --root
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

import { ScreenHtml } from '../components/screen-html.component';

type GLTFResult = GLTF & {
  nodes: {
    Bolt: THREE.Mesh;
    Felge003: THREE.Mesh;
    Felge003_1: THREE.Mesh;
    Felge003_2: THREE.Mesh;
    Felge003_3: THREE.Mesh;
    Felge003_4: THREE.Mesh;
    Reifen002: THREE.Mesh;
    Reifen002_1: THREE.Mesh;
    Reifen002_2: THREE.Mesh;
    Reifen002_3: THREE.Mesh;
    Bolt001: THREE.Mesh;
    Felge003_5: THREE.Mesh;
    Felge003_6: THREE.Mesh;
    Felge003_7: THREE.Mesh;
    Felge003_8: THREE.Mesh;
    Felge003_9: THREE.Mesh;
    Reifen002_4: THREE.Mesh;
    Reifen002_5: THREE.Mesh;
    Reifen002_6: THREE.Mesh;
    Reifen002_7: THREE.Mesh;
    Bolt002: THREE.Mesh;
    Felge003_10: THREE.Mesh;
    Felge003_11: THREE.Mesh;
    Felge003_12: THREE.Mesh;
    Felge003_13: THREE.Mesh;
    Felge003_14: THREE.Mesh;
    Reifen002_8: THREE.Mesh;
    Reifen002_9: THREE.Mesh;
    Reifen002_10: THREE.Mesh;
    Reifen002_11: THREE.Mesh;
    Bolt003: THREE.Mesh;
    Felge003_15: THREE.Mesh;
    Felge003_16: THREE.Mesh;
    Felge003_17: THREE.Mesh;
    Felge003_18: THREE.Mesh;
    Felge003_19: THREE.Mesh;
    Reifen002_12: THREE.Mesh;
    Reifen002_13: THREE.Mesh;
    Reifen002_14: THREE.Mesh;
    Reifen002_15: THREE.Mesh;
    Bolt004: THREE.Mesh;
    Felge003_20: THREE.Mesh;
    Felge003_21: THREE.Mesh;
    Felge003_22: THREE.Mesh;
    Felge003_23: THREE.Mesh;
    Felge003_24: THREE.Mesh;
    Reifen002_16: THREE.Mesh;
    Reifen002_17: THREE.Mesh;
    Reifen002_18: THREE.Mesh;
    Reifen002_19: THREE.Mesh;
    Bolt005: THREE.Mesh;
    Felge003_25: THREE.Mesh;
    Felge003_26: THREE.Mesh;
    Felge003_27: THREE.Mesh;
    Felge003_28: THREE.Mesh;
    Felge003_29: THREE.Mesh;
    Reifen002_20: THREE.Mesh;
    Reifen002_21: THREE.Mesh;
    Reifen002_22: THREE.Mesh;
    Reifen002_23: THREE.Mesh;
    Bolt006: THREE.Mesh;
    Felge003_30: THREE.Mesh;
    Felge003_31: THREE.Mesh;
    Felge003_32: THREE.Mesh;
    Felge003_33: THREE.Mesh;
    Felge003_34: THREE.Mesh;
    Reifen002_24: THREE.Mesh;
    Reifen002_25: THREE.Mesh;
    Reifen002_26: THREE.Mesh;
    Reifen002_27: THREE.Mesh;
    Bolt007: THREE.Mesh;
    Felge003_35: THREE.Mesh;
    Felge003_36: THREE.Mesh;
    Felge003_37: THREE.Mesh;
    Felge003_38: THREE.Mesh;
    Felge003_39: THREE.Mesh;
    Reifen002_28: THREE.Mesh;
    Reifen002_29: THREE.Mesh;
    Reifen002_30: THREE.Mesh;
    Reifen002_31: THREE.Mesh;
    Bolt008: THREE.Mesh;
    Felge003_40: THREE.Mesh;
    Felge003_41: THREE.Mesh;
    Felge003_42: THREE.Mesh;
    Felge003_43: THREE.Mesh;
    Felge003_44: THREE.Mesh;
    Reifen002_32: THREE.Mesh;
    Reifen002_33: THREE.Mesh;
    Reifen002_34: THREE.Mesh;
    Reifen002_35: THREE.Mesh;
    back_camera_border01001: THREE.Mesh;
    back_camera_border_part_01001: THREE.Mesh;
    back_camera_border_part_02001: THREE.Mesh;
    back_camera_border_part_03001: THREE.Mesh;
    back_camera_glass01001: THREE.Mesh;
    back_camera_lens01001: THREE.Mesh;
    back_camera_lens_glass01001: THREE.Mesh;
    back_flash_border01001: THREE.Mesh;
    back_flash_border_part_01001: THREE.Mesh;
    back_flash_glass01001: THREE.Mesh;
    back_flash_lens01001: THREE.Mesh;
    back_flash_lens02001: THREE.Mesh;
    back_glass01001: THREE.Mesh;
    back_glass_part_01001: THREE.Mesh;
    back_panel01001: THREE.Mesh;
    back_panel_logo01001: THREE.Mesh;
    back_panel_part_01001: THREE.Mesh;
    back_panel_part_02001: THREE.Mesh;
    body_side_panel01001: THREE.Mesh;
    body_side_panel_bolts01001: THREE.Mesh;
    body_side_panel_button01001: THREE.Mesh;
    body_side_panel_buttons_part_01001: THREE.Mesh;
    body_side_panel_buttons_part_02001: THREE.Mesh;
    body_side_panel_dynamic01001: THREE.Mesh;
    body_side_panel_part_01001: THREE.Mesh;
    body_side_panel_part_02001: THREE.Mesh;
    body_side_panel_part_03001: THREE.Mesh;
    front_camera_part_01001: THREE.Mesh;
    front_glass01001: THREE.Mesh;
    front_panel01001: THREE.Mesh;
    screen01001: THREE.Mesh;
    screen_border01001: THREE.Mesh;
    screen_part_03001: THREE.Mesh;
    usb01001: THREE.Mesh;
    usb_part_01001: THREE.Mesh;
    Cube: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    ['Logo1.001']: THREE.MeshStandardMaterial;
    ['Metal-Black.001']: THREE.MeshStandardMaterial;
    ['Logo.rim center.001']: THREE.MeshStandardMaterial;
    ['Cromium.001']: THREE.MeshStandardMaterial;
    ['Messing.001']: THREE.MeshStandardMaterial;
    ['Car rubber wheel.001']: THREE.MeshPhysicalMaterial;
    ['Car rubber Glanzwheel.002']: THREE.MeshPhysicalMaterial;
    rot: THREE.MeshStandardMaterial;
    Weis: THREE.MeshStandardMaterial;
    ['plastic_black.001']: THREE.MeshStandardMaterial;
    ['metal_black.001']: THREE.MeshStandardMaterial;
    ['back_black.001']: THREE.MeshStandardMaterial;
    ['mat_plastic_gray_dark.001']: THREE.MeshStandardMaterial;
    ['glass.001']: THREE.MeshStandardMaterial;
    ['camera_lens.001']: THREE.MeshStandardMaterial;
    ['glass_falsh.001']: THREE.MeshStandardMaterial;
    ['chrome.001']: THREE.MeshStandardMaterial;
    ['mat_white.001']: THREE.MeshStandardMaterial;
    ['glossy_yellow.001']: THREE.MeshStandardMaterial;
    ['matte_glass.001']: THREE.MeshStandardMaterial;
    ['mat_black.002']: THREE.MeshStandardMaterial;
    ['chrome_logo_black.001']: THREE.MeshStandardMaterial;
    ['mat_black.003']: THREE.MeshStandardMaterial;
    ['glossy_black.001']: THREE.MeshStandardMaterial;
    ['aluminium_black.001']: THREE.MeshStandardMaterial;
    ['screen.001']: THREE.MeshStandardMaterial;
    ['text_black.001']: THREE.MeshStandardMaterial;
    ['mat_gray_dark.001']: THREE.MeshStandardMaterial;
    ['gold.001']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function SceneModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scenes/scene-v3.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN"
        position={[0, 1.403, 0]}
        rotation={[0, 0, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt"
          castShadow
          receiveShadow
          geometry={nodes.Bolt.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003"
            castShadow
            receiveShadow
            geometry={nodes.Felge003.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_1"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_1.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_2"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_2.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_3"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_3.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_4"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_4.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group name="Tire_Yokohama_ADVAN_Neova_AD08RS" position={[0, 0.342, 0]}>
          <mesh
            name="Reifen002"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_1"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_1.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_2"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_2.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_3"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_3.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN001"
        position={[0, 2.206, 0]}
        rotation={[0, 0.051, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt001"
          castShadow
          receiveShadow
          geometry={nodes.Bolt001.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore001"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_5"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_5.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_6"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_6.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_7"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_7.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_8"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_8.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_9"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_9.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS001"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_4"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_4.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_5"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_5.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_6"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_6.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_7"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_7.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN002"
        position={[0, 3.009, 0]}
        rotation={[0, 0.073, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt002"
          castShadow
          receiveShadow
          geometry={nodes.Bolt002.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore002"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_10"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_10.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_11"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_11.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_12"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_12.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_13"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_13.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_14"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_14.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS002"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_8"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_8.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_9"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_9.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_10"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_10.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_11"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_11.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN003"
        position={[0, 3.822, 0]}
        rotation={[0, 0.073, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt003"
          castShadow
          receiveShadow
          geometry={nodes.Bolt003.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore003"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_15"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_15.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_16"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_16.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_17"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_17.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_18"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_18.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_19"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_19.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS003"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_12"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_12.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_13"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_13.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_14"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_14.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_15"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_15.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN004"
        position={[1.927, 1.403, -0.752]}
        rotation={[0, 0, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt004"
          castShadow
          receiveShadow
          geometry={nodes.Bolt004.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore004"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_20"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_20.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_21"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_21.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_22"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_22.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_23"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_23.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_24"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_24.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS004"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_16"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_16.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_17"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_17.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_18"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_18.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_19"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_19.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN005"
        position={[1.927, 2.209, -0.752]}
        rotation={[0, 0.266, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt005"
          castShadow
          receiveShadow
          geometry={nodes.Bolt005.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore005"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_25"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_25.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_26"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_26.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_27"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_27.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_28"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_28.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_29"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_29.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS005"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_20"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_20.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_21"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_21.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_22"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_22.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_23"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_23.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN006"
        position={[1.12, 2.474, -0.738]}
        rotation={[0.368, -0.751, 0.257]}
        scale={3.006}
      >
        <mesh
          name="Bolt006"
          castShadow
          receiveShadow
          geometry={nodes.Bolt006.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore006"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_30"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_30.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_31"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_31.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_32"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_32.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_33"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_33.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_34"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_34.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS006"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_24"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_24.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_25"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_25.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_26"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_26.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_27"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_27.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN007"
        position={[-0.899, 1.403, 1.928]}
        rotation={[0, 0, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt007"
          castShadow
          receiveShadow
          geometry={nodes.Bolt007.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore007"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_35"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_35.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_36"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_36.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_37"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_37.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_38"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_38.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_39"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_39.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS007"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_28"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_28.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_29"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_29.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_30"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_30.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_31"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_31.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Car_tires,_Speedline_corse__Yokohama_ADVAN008"
        position={[-0.899, 2.228, 1.928]}
        rotation={[0, 0.115, Math.PI / 2]}
        scale={3.006}
      >
        <mesh
          name="Bolt008"
          castShadow
          receiveShadow
          geometry={nodes.Bolt008.geometry}
          material={materials['Logo1.001']}
          position={[0, 0.342, 0]}
        />
        <group
          name="Rim_speedline_corse_SL8_Dominatore008"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Felge003_40"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_40.geometry}
            material={materials['Metal-Black.001']}
          />
          <mesh
            name="Felge003_41"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_41.geometry}
            material={materials['Logo1.001']}
          />
          <mesh
            name="Felge003_42"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_42.geometry}
            material={materials['Logo.rim center.001']}
          />
          <mesh
            name="Felge003_43"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_43.geometry}
            material={materials['Cromium.001']}
          />
          <mesh
            name="Felge003_44"
            castShadow
            receiveShadow
            geometry={nodes.Felge003_44.geometry}
            material={materials['Messing.001']}
          />
        </group>
        <group
          name="Tire_Yokohama_ADVAN_Neova_AD08RS008"
          position={[0, 0.342, 0]}
        >
          <mesh
            name="Reifen002_32"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_32.geometry}
            material={materials['Car rubber wheel.001']}
          />
          <mesh
            name="Reifen002_33"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_33.geometry}
            material={materials['Car rubber Glanzwheel.002']}
          />
          <mesh
            name="Reifen002_34"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_34.geometry}
            material={materials.rot}
          />
          <mesh
            name="Reifen002_35"
            castShadow
            receiveShadow
            geometry={nodes.Reifen002_35.geometry}
            material={materials.Weis}
          />
        </group>
      </group>
      <group
        name="Apple_iPhone_14_Pro_Space_Black001"
        position={[-0.227, 2.415, 1.064]}
        rotation={[-0.142, 0.547, 0.074]}
        scale={0.192}
      >
        <mesh
          name="back_camera_border01001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_border01001.geometry}
          material={materials['plastic_black.001']}
          position={[1.253, 4.984, -0.535]}
        />
        <mesh
          name="back_camera_border_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_border_part_01001.geometry}
          material={materials['metal_black.001']}
          position={[1.253, 4.981, -0.441]}
        />
        <mesh
          name="back_camera_border_part_02001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_border_part_02001.geometry}
          material={materials['back_black.001']}
          position={[1.253, 4.981, -0.545]}
        />
        <mesh
          name="back_camera_border_part_03001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_border_part_03001.geometry}
          material={materials['mat_plastic_gray_dark.001']}
          position={[1.298, 4.805, -0.423]}
        />
        <mesh
          name="back_camera_glass01001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_glass01001.geometry}
          material={materials['glass.001']}
          position={[1.253, 4.981, -0.58]}
        />
        <mesh
          name="back_camera_lens01001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_lens01001.geometry}
          material={materials['camera_lens.001']}
          position={[1.307, 4.963, -0.412]}
        />
        <mesh
          name="back_camera_lens_glass01001"
          castShadow
          receiveShadow
          geometry={nodes.back_camera_lens_glass01001.geometry}
          material={materials['glass.001']}
          position={[0.356, 4.978, -0.462]}
        />
        <mesh
          name="back_flash_border01001"
          castShadow
          receiveShadow
          geometry={nodes.back_flash_border01001.geometry}
          material={materials['glass_falsh.001']}
          position={[0.359, 6.336, -0.282]}
        />
        <mesh
          name="back_flash_border_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.back_flash_border_part_01001.geometry}
          material={materials['chrome.001']}
          position={[0.359, 6.336, -0.227]}
        />
        <mesh
          name="back_flash_glass01001"
          castShadow
          receiveShadow
          geometry={nodes.back_flash_glass01001.geometry}
          material={materials['glass.001']}
          position={[0.359, 6.336, -0.355]}
        />
        <mesh
          name="back_flash_lens01001"
          castShadow
          receiveShadow
          geometry={nodes.back_flash_lens01001.geometry}
          material={materials['mat_white.001']}
          position={[0.359, 6.336, -0.261]}
        />
        <mesh
          name="back_flash_lens02001"
          castShadow
          receiveShadow
          geometry={nodes.back_flash_lens02001.geometry}
          material={materials['glossy_yellow.001']}
          position={[0.359, 6.336, -0.249]}
        />
        <mesh
          name="back_glass01001"
          castShadow
          receiveShadow
          geometry={nodes.back_glass01001.geometry}
          material={materials['matte_glass.001']}
          position={[0.003, 0, -0.29]}
        />
        <mesh
          name="back_glass_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.back_glass_part_01001.geometry}
          material={materials['glass.001']}
          position={[1.233, 4.98, -0.37]}
        />
        <mesh
          name="back_panel01001"
          castShadow
          receiveShadow
          geometry={nodes.back_panel01001.geometry}
          material={materials['mat_black.002']}
          position={[0.003, 0, -0.268]}
        />
        <mesh
          name="back_panel_logo01001"
          castShadow
          receiveShadow
          geometry={nodes.back_panel_logo01001.geometry}
          material={materials['chrome_logo_black.001']}
          position={[-0.028, 0.087, -0.182]}
        />
        <mesh
          name="back_panel_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.back_panel_part_01001.geometry}
          material={materials['mat_black.002']}
          position={[1.233, 4.98, -0.332]}
        />
        <mesh
          name="back_panel_part_02001"
          castShadow
          receiveShadow
          geometry={nodes.back_panel_part_02001.geometry}
          material={materials['mat_black.003']}
          position={[1.194, 4.726, -0.084]}
        />
        <mesh
          name="body_side_panel01001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel01001.geometry}
          material={materials['metal_black.001']}
          position={[0.003, 0, 0.192]}
        />
        <mesh
          name="body_side_panel_bolts01001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_bolts01001.geometry}
          material={materials['chrome.001']}
          position={[0.003, -7.354, 0.193]}
        />
        <mesh
          name="body_side_panel_button01001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_button01001.geometry}
          material={materials['metal_black.001']}
          position={[3.595, 1.815, 0.192]}
        />
        <mesh
          name="body_side_panel_buttons_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_buttons_part_01001.geometry}
          material={materials['metal_black.001']}
          position={[-3.588, 2.178, 0.192]}
        />
        <mesh
          name="body_side_panel_buttons_part_02001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_buttons_part_02001.geometry}
          material={materials['metal_black.001']}
          position={[-3.566, 4.236, 0.191]}
        />
        <mesh
          name="body_side_panel_dynamic01001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_dynamic01001.geometry}
          material={materials['glossy_black.001']}
          position={[0.216, -7.323, 0.192]}
        />
        <mesh
          name="body_side_panel_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_part_01001.geometry}
          material={materials['aluminium_black.001']}
          position={[0.003, 0, 0.192]}
        />
        <mesh
          name="body_side_panel_part_02001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_part_02001.geometry}
          material={materials['aluminium_black.001']}
          position={[3.578, -2.01, 0.192]}
        />
        <mesh
          name="body_side_panel_part_03001"
          castShadow
          receiveShadow
          geometry={nodes.body_side_panel_part_03001.geometry}
          material={materials['mat_black.003']}
          position={[-0.035, -1.85, 0.183]}
        />
        <mesh
          name="front_camera_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.front_camera_part_01001.geometry}
          material={materials['mat_black.003']}
          position={[0.003, 6.757, 0.453]}
        />
        <mesh
          name="front_glass01001"
          castShadow
          receiveShadow
          geometry={nodes.front_glass01001.geometry}
          material={materials['glass.001']}
          position={[0.003, 0, 0.578]}
        />
        <mesh
          name="front_panel01001"
          castShadow
          receiveShadow
          geometry={nodes.front_panel01001.geometry}
          material={materials['back_black.001']}
          position={[0.003, 0, 0.543]}
        />
        <mesh
          name="screen01001"
          geometry={nodes.screen01001.geometry}
          position={[0.003, 0, 0.542]}
        >
          <meshStandardMaterial transparent opacity={0} />
          <ScreenHtml />
        </mesh>
        <mesh
          name="screen_border01001"
          castShadow
          receiveShadow
          geometry={nodes.screen_border01001.geometry}
          material={materials['text_black.001']}
          position={[0.003, 0, 0.542]}
        />
        <mesh
          name="screen_part_03001"
          castShadow
          receiveShadow
          geometry={nodes.screen_part_03001.geometry}
          material={materials['mat_gray_dark.001']}
          position={[0.009, 6.555, 0.542]}
        />
        <mesh
          name="usb01001"
          castShadow
          receiveShadow
          geometry={nodes.usb01001.geometry}
          material={materials['chrome.001']}
          position={[0.002, -6.943, 0.192]}
        />
        <mesh
          name="usb_part_01001"
          castShadow
          receiveShadow
          geometry={nodes.usb_part_01001.geometry}
          material={materials['gold.001']}
          position={[0.003, -6.951, 0.167]}
        />
      </group>
      <PerspectiveCamera
        name="Camera"
        makeDefault
        far={1000}
        near={0.1}
        fov={22.895}
        position={[2.766, 2.067, 9.27]}
        rotation={[0.06, 0.376, -0.022]}
      />
      <spotLight
        name="Spot"
        intensity={20000}
        angle={0.553}
        penumbra={1}
        decay={2}
        position={[0.621, 18.688, 1.783]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.358}
        castShadow
        shadow-mapSize-width={2048} // Increased shadow map resolution
        shadow-mapSize-height={2048} // Increased shadow map resolution
        shadow-bias={-0.0001} // Bias to reduce shadow acne
      />
      <spotLight
        name="Spot001"
        intensity={7000}
        angle={Math.PI / 8}
        penumbra={1}
        decay={2}
        color="#ff51ce"
        position={[3.434, 14.363, 4.128]}
        rotation={[-1.436, 0.192, -0.032]}
        castShadow
        shadow-mapSize-width={2048} // Increased shadow map resolution
        shadow-mapSize-height={2048} // Increased shadow map resolution
        shadow-bias={-0.0001} // Bias to reduce shadow acne
      />
      <spotLight
        name="Spot002"
        intensity={20000}
        angle={0.489}
        penumbra={1}
        decay={2}
        color="#8cffe0"
        position={[-5.274, 10.559, -3.462]}
        rotation={[-1.925, -0.405, -0.114]}
        castShadow
        shadow-mapSize-width={2048} // Increased shadow map resolution
        shadow-mapSize-height={2048} // Increased shadow map resolution
        shadow-bias={-0.0001} // Bias to reduce shadow acne
      />
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials['Material.001']}
      />
      <mesh
        name="Plane"
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[0, -4.474, 0]}
      />
    </group>
  );
}

useGLTF.preload('/scenes/scene-v3.glb');
