import './reset.css';
import './global.css';
// import '@pigment-css/react/styles.css';

export const metadata = {
  title: 'Welcome to presento-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
