import './reset.css';
import './global.css';
import './background-animation.css';
import './animation.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import React, { PropsWithChildren } from 'react';
import { getUser } from '@presento/presento-web-modules/user';

import { ScreenLayout, theme } from '@presento/presento-web-design-system';

export const metadata = {
  title: 'Welcome to presento-web',
  description: 'Generated by create-nx-workspace',
};

const RootLayout: React.FC<PropsWithChildren> = async (props) => {
  const { children } = props;

  const user = await getUser();

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <ScreenLayout user={user}>{children}</ScreenLayout>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
