/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 apps/presento-web/public/scenes/scene-v1.glb --types --shadows --keepnames --root
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import {
  useGLTF,
  PerspectiveCamera,
  Html,
  OrthographicCamera,
} from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import './test.css';

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane003: THREE.Mesh;
    back_camera_border01: THREE.Mesh;
    back_camera_border_part_01: THREE.Mesh;
    back_camera_border_part_02: THREE.Mesh;
    back_camera_border_part_03: THREE.Mesh;
    back_camera_glass01: THREE.Mesh;
    back_camera_lens01: THREE.Mesh;
    back_camera_lens_glass01: THREE.Mesh;
    back_flash_border01: THREE.Mesh;
    back_flash_border_part_01: THREE.Mesh;
    back_flash_glass01: THREE.Mesh;
    back_flash_lens01: THREE.Mesh;
    back_flash_lens02: THREE.Mesh;
    back_glass01: THREE.Mesh;
    back_glass_part_01: THREE.Mesh;
    back_panel01: THREE.Mesh;
    back_panel_logo01: THREE.Mesh;
    back_panel_part_01: THREE.Mesh;
    back_panel_part_02: THREE.Mesh;
    body_side_panel01: THREE.Mesh;
    body_side_panel_bolts01: THREE.Mesh;
    body_side_panel_button01: THREE.Mesh;
    body_side_panel_buttons_part_01: THREE.Mesh;
    body_side_panel_buttons_part_02: THREE.Mesh;
    body_side_panel_dynamic01: THREE.Mesh;
    body_side_panel_part_01: THREE.Mesh;
    body_side_panel_part_02: THREE.Mesh;
    body_side_panel_part_03: THREE.Mesh;
    front_camera_border01: THREE.Mesh;
    front_camera_border_part_01: THREE.Mesh;
    front_camera_lens01: THREE.Mesh;
    front_camera_part_01: THREE.Mesh;
    front_glass01: THREE.Mesh;
    front_panel01: THREE.Mesh;
    screen01: THREE.Mesh;
    screen_border01: THREE.Mesh;
    screen_part_01: THREE.Mesh;
    screen_part_03: THREE.Mesh;
    usb01: THREE.Mesh;
    usb_part_01: THREE.Mesh;
  };
  materials: {
    ['Material.024']: THREE.MeshStandardMaterial;
    ['Material.023']: THREE.MeshStandardMaterial;
    ['Material.025']: THREE.MeshStandardMaterial;
    metal_blue: THREE.MeshStandardMaterial;
    ['plastic_black.001']: THREE.MeshStandardMaterial;
    ['metal_black.001']: THREE.MeshStandardMaterial;
    ['back_black.001']: THREE.MeshStandardMaterial;
    ['mat_plastic_gray_dark.001']: THREE.MeshStandardMaterial;
    ['glass.001']: THREE.MeshStandardMaterial;
    ['camera_lens.001']: THREE.MeshStandardMaterial;
    ['glass_falsh.001']: THREE.MeshStandardMaterial;
    ['chrome.001']: THREE.MeshStandardMaterial;
    ['mat_white.001']: THREE.MeshStandardMaterial;
    ['glossy_yellow.001']: THREE.MeshStandardMaterial;
    matte_glass: THREE.MeshStandardMaterial;
    ['mat_black.002']: THREE.MeshStandardMaterial;
    ['chrome_logo_black.001']: THREE.MeshStandardMaterial;
    ['mat_black.003']: THREE.MeshStandardMaterial;
    ['glossy_black.001']: THREE.MeshStandardMaterial;
    ['aluminium_black.001']: THREE.MeshStandardMaterial;
    screen: THREE.MeshStandardMaterial;
    ['text_black.001']: THREE.MeshStandardMaterial;
    ['mat_gray_dark.001']: THREE.MeshStandardMaterial;
    ['gold.001']: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function SceneModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scenes/scene-v1.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <spotLight
        name="Spot"
        intensity={0.1}
        angle={Math.PI / 8}
        penumbra={0.15}
        decay={2}
        color="#fff2d1"
        position={[1.618, 2.194, -0.138]}
        rotation={[-Math.PI / 2, 0.458, 0]}
        scale={5}
      />
      <PerspectiveCamera
        name="x-scene-camera"
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={30}
        position={[0.858, 0.751, 1.624]}
        rotation={[-0.607, 0.412, 0.271]}
        scale={5}
      />
      <spotLight
        name="Spot001"
        intensity={0.1}
        angle={Math.PI / 8}
        penumbra={0.15}
        decay={2}
        color="#f2f6ff"
        position={[-0.763, 1.331, -0.138]}
        rotation={[-Math.PI / 2, -0.419, 0]}
        scale={5}
      />
      <spotLight
        name="Spot002"
        intensity={0.1}
        angle={Math.PI / 8}
        penumbra={0.15}
        decay={2}
        color="#fff2d1"
        position={[13.715, 24.835, -0.138]}
        rotation={[-Math.PI / 2, 0.458, 0]}
        scale={5}
      />
      <mesh
        name="Plane"
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.024']}
        position={[0.229, -0.46, -0.138]}
      />
      <mesh
        name="Plane001"
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Material.023']}
        position={[0.229, -1.741, -0.138]}
      />
      <mesh
        name="Plane002"
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['Material.025']}
        position={[-0.518, -0.164, -0.167]}
      />
      <mesh
        name="Plane003"
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.metal_blue}
        position={[-0.145, -0.343, -0.167]}
      />
      <mesh
        name="back_camera_border01"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_border01.geometry}
        material={materials['plastic_black.001']}
        position={[0.308, -0.461, -0.388]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_camera_border_part_01"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_border_part_01.geometry}
        material={materials['metal_black.001']}
        position={[0.308, -0.457, -0.388]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_camera_border_part_02"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_border_part_02.geometry}
        material={materials['back_black.001']}
        position={[0.305, -0.461, -0.388]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_camera_border_part_03"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_border_part_03.geometry}
        material={materials['mat_plastic_gray_dark.001']}
        position={[0.302, -0.455, -0.385]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_camera_glass01"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_glass01.geometry}
        material={materials['glass.001']}
        position={[0.308, -0.462, -0.388]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_camera_lens01"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_lens01.geometry}
        material={materials['camera_lens.001']}
        position={[0.308, -0.454, -0.388]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_camera_lens_glass01"
        castShadow
        receiveShadow
        geometry={nodes.back_camera_lens_glass01.geometry}
        material={materials['glass.001']}
        position={[0.248, -0.458, -0.387]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_flash_border01"
        castShadow
        receiveShadow
        geometry={nodes.back_flash_border01.geometry}
        material={materials['glass_falsh.001']}
        position={[0.248, -0.45, -0.455]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_flash_border_part_01"
        castShadow
        receiveShadow
        geometry={nodes.back_flash_border_part_01.geometry}
        material={materials['chrome.001']}
        position={[0.248, -0.447, -0.455]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_flash_glass01"
        castShadow
        receiveShadow
        geometry={nodes.back_flash_glass01.geometry}
        material={materials['glass.001']}
        position={[0.248, -0.453, -0.455]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_flash_lens01"
        castShadow
        receiveShadow
        geometry={nodes.back_flash_lens01.geometry}
        material={materials['mat_white.001']}
        position={[0.248, -0.448, -0.455]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_flash_lens02"
        castShadow
        receiveShadow
        geometry={nodes.back_flash_lens02.geometry}
        material={materials['glossy_yellow.001']}
        position={[0.248, -0.448, -0.455]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_glass01"
        castShadow
        receiveShadow
        geometry={nodes.back_glass01.geometry}
        material={materials.matte_glass}
        position={[0.246, -0.448, -0.264]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_glass_part_01"
        castShadow
        receiveShadow
        geometry={nodes.back_glass_part_01.geometry}
        material={materials['glass.001']}
        position={[0.282, -0.453, -0.396]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_panel01"
        castShadow
        receiveShadow
        geometry={nodes.back_panel01.geometry}
        material={materials['mat_black.002']}
        position={[0.245, -0.447, -0.258]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_panel_logo01"
        castShadow
        receiveShadow
        geometry={nodes.back_panel_logo01.geometry}
        material={materials['chrome_logo_black.001']}
        position={[0.223, -0.447, -0.148]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_panel_part_01"
        castShadow
        receiveShadow
        geometry={nodes.back_panel_part_01.geometry}
        material={materials['mat_black.002']}
        position={[0.275, -0.453, -0.394]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="back_panel_part_02"
        castShadow
        receiveShadow
        geometry={nodes.back_panel_part_02.geometry}
        material={materials['mat_black.003']}
        position={[0.289, -0.438, -0.375]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel01"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel01.geometry}
        material={materials['metal_black.001']}
        position={[0.194, -0.43, -0.047]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_bolts01"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_bolts01.geometry}
        material={materials['chrome.001']}
        position={[0.229, -0.429, 0.229]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_button01"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_button01.geometry}
        material={materials['metal_black.001']}
        position={[0.409, -0.419, -0.229]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_buttons_part_01"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_buttons_part_01.geometry}
        material={materials['metal_black.001']}
        position={[0.048, -0.437, -0.247]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_buttons_part_02"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_buttons_part_02.geometry}
        material={materials['metal_black.001']}
        position={[0.049, -0.439, -0.35]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_dynamic01"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_dynamic01.geometry}
        material={materials['glossy_black.001']}
        position={[0.259, -0.428, 0.228]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_part_01"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_part_01.geometry}
        material={materials['aluminium_black.001']}
        position={[0.229, -0.428, -0.138]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_part_02"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_part_02.geometry}
        material={materials['aluminium_black.001']}
        position={[0.407, -0.419, -0.038]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="body_side_panel_part_03"
        castShadow
        receiveShadow
        geometry={nodes.body_side_panel_part_03.geometry}
        material={materials['mat_black.003']}
        position={[0.229, -0.429, 0.119]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="front_camera_border01"
        castShadow
        receiveShadow
        geometry={nodes.front_camera_border01.geometry}
        material={materials['mat_plastic_gray_dark.001']}
        position={[0.265, -0.412, -0.466]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="front_camera_border_part_01"
        castShadow
        receiveShadow
        geometry={nodes.front_camera_border_part_01.geometry}
        material={materials['back_black.001']}
        position={[0.265, -0.41, -0.465]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="front_camera_lens01"
        castShadow
        receiveShadow
        geometry={nodes.front_camera_lens01.geometry}
        material={materials['camera_lens.001']}
        position={[0.265, -0.413, -0.466]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="front_camera_part_01"
        castShadow
        receiveShadow
        geometry={nodes.front_camera_part_01.geometry}
        material={materials['mat_black.003']}
        position={[0.246, -0.412, -0.477]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="front_glass01"
        castShadow
        receiveShadow
        geometry={nodes.front_glass01.geometry}
        material={materials['glass.001']}
        position={[0.228, -0.409, -0.16]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="front_panel01"
        castShadow
        receiveShadow
        geometry={nodes.front_panel01.geometry}
        material={materials['back_black.001']}
        position={[0.228, -0.41, -0.164]}
        rotation={[-1.567, -0.051, 0]}
      />

      <mesh
        name="screen01"
        castShadow
        receiveShadow
        geometry={nodes.screen01.geometry}
        material={materials.screen}
        position={[0.228, -0.41, -0.239]}
        rotation={[-1.567, -0.051, 0]}
      >
        <Html
          scale={0.1}
          position={[0, 0, 0.08]}
          style={{ background: 'red', width: 100, height: 300 }}
          transform
          occlude="blending"
        >
          <div
            style={{
              background: 'green',
              zIndex: 10,
            }}
          >
            test text
          </div>
          <p>test text</p>
        </Html>
      </mesh>

      <mesh
        name="screen_border01"
        castShadow
        receiveShadow
        geometry={nodes.screen_border01.geometry}
        material={materials['text_black.001']}
        position={[0.228, -0.411, -0.137]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="screen_part_01"
        castShadow
        receiveShadow
        geometry={nodes.screen_part_01.geometry}
        material={materials['mat_black.003']}
        position={[0.239, -0.409, -0.466]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="screen_part_03"
        castShadow
        receiveShadow
        geometry={nodes.screen_part_03.geometry}
        material={materials['mat_gray_dark.001']}
        position={[0.209, -0.41, -0.466]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="usb01"
        castShadow
        receiveShadow
        geometry={nodes.usb01.geometry}
        material={materials['chrome.001']}
        position={[0.229, -0.429, 0.211]}
        rotation={[-1.567, -0.051, 0]}
      />
      <mesh
        name="usb_part_01"
        castShadow
        receiveShadow
        geometry={nodes.usb_part_01.geometry}
        material={materials['gold.001']}
        position={[0.229, -0.433, 0.21]}
        rotation={[-1.567, -0.051, 0]}
      />
    </group>
  );
}

useGLTF.preload('/scenes/scene-v1.glb');
